{
	"version": 1699524010,
	"fileList": [
		"data.js",
		"c2runtime.js",
		"jquery-3.4.1.min.js",
		"offlineClient.js",
		"images/bg-sheet0.png",
		"images/spritefont_score.png",
		"images/btn_play-sheet0.png",
		"images/bg_score-sheet0.png",
		"images/ball-sheet0.png",
		"images/ball-sheet1.png",
		"images/miniball-sheet0.png",
		"images/miniball-sheet1.png",
		"images/highscore-sheet0.png",
		"images/bg_gamename-sheet0.png",
		"images/playtext-sheet0.png",
		"images/scoretext-sheet0.png",
		"images/miniball_sample-sheet0.png",
		"images/sprite-sheet0.png",
		"images/sprite2-sheet0.png",
		"images/volume-sheet0.png",
		"images/volume-sheet1.png",
		"media/gameover.m4a",
		"media/gameover.ogg",
		"media/pop gp 006.ogg",
		"media/pop gp 006.m4a",
		"media/pop gp 001.ogg",
		"media/pop gp 001.m4a",
		"icon-16.png",
		"icon-32.png",
		"icon-114.png",
		"icon-128.png",
		"icon-256.png",
		"loading-logo.png"
	]
}